css с препроцессорами
htmlacademy-adaptive/1124569-sedona-20 pull request #4
Opened 2020-08-18 16:41 UTC by Rudolf31

2020-08-19 20:57 UTC, raccoonroman requested changes
удали лишние файлы, типа  `source/less/. — копия (2) — копия — копия.less`

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +      <img src="img/text-sedona-index.svg" width="282" class="hero-title">
`hero-title` это скорее бэм-элемент

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +            <h1 class="advantages__title advantages__white-title">НАСТОЯЩИЙ ГОРОДОК</h1>
правильно модификатор писать так `class="advantages__title advantages__title--white"`

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +        <li class="advantages__item blue-block advantages__blue-block">
выше у тебя див с классом `advantages__blue-block` используй здесь так же. Не усложняй разметку

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +          <p class="advantages__description advantages__white-description white-numbers">№2</p>
прописывай модификаторы правильно, через двойной дефис

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +        <div class="advantages__item-gray">
`advantages__item` у тебя прописан для лишек (li). Здесь уже див. Дочерним элементом списка (ul) может быть только элемент (li).

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +        <div class="advantages__item-gray">
не `advantages__item-gray`, а `advantages__item advantages__item--gray`. Очевидно, что серый фон является модификатором

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +          <li class="advantages__item devil">
devil не нужно делать отдельным бэм-блоком

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +            <p class="advantages__description numbers">№3</p>
numbers не нужно  делать отдельным бэм-блоком

2020-08-19 20:57 UTC, raccoonroman commented on source/index.html
> +      <img src="img/bg-map-mobile@1x.jpg " width="320">
для растровых изображений размеры можно не писать

2020-08-19 20:57 UTC, raccoonroman commented on source/less/advantages.less
> +  padding-top: 0px;
когда значение 0, единицы измерения можно не писать

2020-08-19 20:57 UTC, raccoonroman commented on source/less/advantages.less
> +.advantages__blue-block p:last-of-type {
используй преимущества препроцесоров - вложеность.

2020-08-19 20:57 UTC, raccoonroman commented on source/less/advantages.less
> +.advantages {
бэм-блоки должны находится в отдельной папке
https://up.htmlacademy.ru/adaptive/20/criteries#b13

2020-08-19 20:57 UTC, raccoonroman commented on source/less/variables.less
> +  text-align: center;
вместо таких стилей советую использовать миксины, чтобы на выходе не было этого селектора, так как ты его не использешь напрямую для элементов

2020-08-19 20:57 UTC, raccoonroman commented on source/less/variables.less
> +  text-align: center;
и в этом файле должны быть только переменные, никаких селекторов

2020-08-19 20:57 UTC, raccoonroman commented on source/less/search.less
> +  .center;
разширения/миксины всегда пиши в начале селектора, так как бывают случаи, когда некоторые свойства разширений/миксинов нужно переопределить внутри текущего селектора

2020-08-19 20:57 UTC, raccoonroman commented on source/less/advantages.less
> +.numbers::after {
используй вложеность http://lesscss.org/features/#parent-selectors-feature

2020-08-19 20:57 UTC, raccoonroman commented on source/less/advantages.less
> +.numbers::after {
длинный дефис можно вставить напрямю в разметку

2020-08-19 20:57 UTC, raccoonroman commented on source/less/advantages.less
> +.numbers {
это уже другой бэм-блок, который должен находится в своем файле. (Но лучше просто избавиться от этого бэм-блока)

2020-08-19 20:57 UTC, raccoonroman commented on source/less/advantages.less
> +.advantages__item-gray .devil {
devil - другой бэм-блок, должен быть в своем файле. Но по правильному - сделай его модификатором

2020-08-19 20:57 UTC, raccoonroman commented on source/less/block-white.less
> +.white-block {
название файла не совпадает с названием бэм-блока

2020-08-19 20:57 UTC, raccoonroman commented on source/less/global.less
> +  font-family: 'PT Sans','Lato', sans-serif;
Lato не является веб-безопасным шрифтом

2020-08-19 20:57 UTC, raccoonroman commented on source/less/global.less
> +  outline: none;
глоб. стили https://up.htmlacademy.ru/adaptive/20/criteries#d16

2020-08-19 20:57 UTC, raccoonroman commented on source/less/global.less
> +.ul-element {
используй миксин

2020-08-19 20:57 UTC, raccoonroman commented on source/less/global.less
> +.ul-element {
и в него должны входить три свойства, для того чтобы сбросить стили по умолчанию для списков: margin, padding, list-style. Сам миксин назови list-reset например

2020-08-19 20:57 UTC, raccoonroman commented on source/less/global.less
> +  list-style-type: none;
https://up.htmlacademy.ru/adaptive/20/criteries#d16

2020-08-19 20:57 UTC, raccoonroman commented on source/less/hero.less
> +.hero-title {
это уже другой бэм-блок

2020-08-19 20:57 UTC, raccoonroman commented on source/less/hero.less
> +.photo-hero {
другой бэм-блок

2020-08-19 20:57 UTC, raccoonroman commented on source/less/hero.less
> +.form-hero {
другой бэм-блок

2020-08-19 20:57 UTC, raccoonroman commented on source/less/main-nav.less
> +.page-header__logo {
все бэм-блоки должны находится в своих одноименных файлах

2020-08-19 20:57 UTC, raccoonroman commented on source/less/main-nav.less
> +  margin-bottom: 0;
используй миксин list-reset, про который писал выше

2020-08-19 20:57 UTC, raccoonroman commented on source/less/main-nav.less
> +  box-shadow: 0px 1px 0px rgba(1, 1, 1, 0.2), inset 0px 1px 0px rgba(255, 255, 255, 0.2);
единицы измерений для нулевых значений можно не писать

2020-08-19 20:57 UTC, raccoonroman commented on source/less/main-nav.less
> +  box-shadow: 0px 1px 0px rgba(1, 1, 1, 0.2), inset 0px 1px 0px rgba(255, 255, 255, 0.2);
вместо `rgba(255, 255, 255, 0.2)` пиши `rgba(#ffffff, 0.2)`

2020-08-19 20:57 UTC, raccoonroman commented on source/less/main-nav.less
> +  padding: 7px 5.5px;
всегда используй целые значения. Дробные "плохо рендерятся"

2020-08-19 20:57 UTC, raccoonroman commented on source/less/photos.less
> +.photos__item:first-of-type {
 используй преимущества препроцесоров http://lesscss.org/features/#parent-selectors-feature

2020-08-19 20:57 UTC, raccoonroman commented on source/less/photos.less
> +.photos__item:after {
псевдоэлемент пиши через двойное двоеточие `::`

2020-08-24 12:24 UTC, Rudolf31 commented on source/index.html
> +        <li class="advantages__item blue-block advantages__blue-block">
исправлено

2020-08-24 12:24 UTC, Rudolf31 commented on source/index.html
> +          <p class="advantages__description advantages__white-description white-numbers">№2</p>
поправил

2020-08-24 12:25 UTC, Rudolf31 commented on source/index.html
> +        <div class="advantages__item-gray">
сделал

2020-08-25 08:41 UTC, Rudolf31 commented on source/less/advantages.less
> +  padding-top: 0px;
да, забыл, но исправил

2020-08-25 08:51 UTC, Rudolf31 commented on source/less/advantages.less
> +.numbers {
перенес в отдельную папку

2020-08-26 14:06 UTC, Rudolf31 commented on source/less/advantages.less
> +.advantages__item-gray .devil {
сделал бэм блоком

2020-08-26 14:13 UTC, Rudolf31 commented on source/less/block-white.less
> +.white-block {
исправил

2020-08-27 11:57 UTC, Rudolf31 commented on source/index.html
> +          <li class="advantages__item devil">
вроде правильно исправил

2020-08-27 12:10 UTC, Rudolf31 commented on source/index.html
> +            <p class="advantages__description numbers">№3</p>
все исправил

2020-08-27 12:11 UTC, Rudolf31 commented on source/index.html
> +      <img src="img/bg-map-mobile@1x.jpg " width="320">
я ее удалил, постараюсь сделать с помощью css

2020-08-27 12:12 UTC, Rudolf31 commented on source/less/advantages.less
> +.advantages__blue-block p:last-of-type {
да, конвертор мне в помощь, сделал

2020-08-27 12:31 UTC, Rudolf31 commented on source/less/photos.less
> +.photos__item:after {
забыл, но исправил

2020-08-27 12:37 UTC, Rudolf31 commented on source/less/main-nav.less
> +  box-shadow: 0px 1px 0px rgba(1, 1, 1, 0.2), inset 0px 1px 0px rgba(255, 255, 255, 0.2);
исправил

2020-08-27 12:38 UTC, Rudolf31 commented on source/less/main-nav.less
> +  padding: 7px 5.5px;
понял, готово

2020-08-27 12:40 UTC, Rudolf31 commented on source/less/photos.less
> +.photos__item:first-of-type {
сделал

2020-08-27 12:45 UTC, Rudolf31 commented on source/index.html
> +      <img src="img/text-sedona-index.svg" width="282" class="hero-title">
сделал модификацией

2020-08-27 21:53 UTC, Rudolf31 commented on source/less/advantages.less
> +.numbers::after {
исправил

2020-08-27 22:13 UTC, Rudolf31 commented on source/less/hero.less
> +.hero-title {
поменял

2020-08-27 22:13 UTC, Rudolf31 commented on source/less/hero.less
> +.photo-hero {
и это тоже поменял

2020-08-27 22:14 UTC, Rudolf31 commented on source/less/hero.less
> +.form-hero {
тоже сменил

2020-08-27 22:47 UTC, Rudolf31 commented on source/less/main-nav.less
> +.page-header__logo {
сделал

2020-08-28 10:51 UTC, Rudolf31 commented on source/form.html
> +    <link href="https://fonts.googleapis.com/css2?family=Lato&family=PT+Sans:wght@400;700&display=swap" rel="stylesheet">
убрал

2020-08-29 13:11 UTC, Rudolf31 commented on source/form.html
> +          <ul class="form__list ul-element">
убрал и заменил

2020-08-29 13:13 UTC, Rudolf31 commented on source/less/global.less
> +  font-family: 'PT Sans','Lato', sans-serif;
убрал

2020-08-29 13:18 UTC, Rudolf31 commented on source/less/global.less
> +.ul-element {
написал и заменил

2020-08-29 13:19 UTC, Rudolf31 commented on source/less/main-nav.less
> +  margin-bottom: 0;
сделал

2020-08-29 14:09 UTC, Rudolf31 commented on source/less/search.less
> +  .center;
переставил везде

2020-08-29 14:25 UTC, Rudolf31 commented on source/less/advantages.less
> +.advantages {
создал папку

2020-08-30 21:08 UTC, Rudolf31 commented on source/less/variables.less
> +  text-align: center;
создал другой файл

2020-08-31 20:48 UTC, Rudolf31 commented on source/less/global.less
> +  outline: none;
убрал

2020-08-31 20:48 UTC, Rudolf31 commented on source/less/global.less
> +  list-style-type: none;
убрал

2020-09-01 13:56 UTC, raccoonroman requested changes

2020-09-01 13:56 UTC, raccoonroman commented on source/form.html
> +        <img src="img/text-sedona.svg" width="229px">
не исправлено. Нужно убрать единицы измерений и прописать еще height, см. критиерий https://up.htmlacademy.ru/adaptive/20/criteries#d1

2020-09-01 13:56 UTC, raccoonroman commented on source/form.html
> +        <li><a href="#" class="socials__link"><img src="img/icon-twitter.svg"  alt="">twitter</a></li>
нужно указать размеры https://up.htmlacademy.ru/adaptive/20/criteries#d1

2020-09-01 13:56 UTC, raccoonroman commented on source/form.html
> +        <li><a href="#" class="socials__link"><img src="img/icon-twitter.svg"  alt="">twitter</a></li>
ссылкам нужно добавить текстовое описание https://up.htmlacademy.ru/adaptive/20/criteries#d18

2020-09-01 13:56 UTC, raccoonroman commented on source/index.html
> +      <img src="img/text-sedona-index.svg" width="282" class="hero__title">
нужно указать еще height

2020-09-01 13:56 UTC, raccoonroman commented on source/index.html
> +      <div class="block-white"></div>
белую маску лучше выводить стилями, чтобы не было лишнего элемента

2020-09-01 13:56 UTC, raccoonroman commented on source/index.html
> +            <p class="advantages__description advantages__description--white">— №1 —</p>
лучше не писать каждому вложенному элементу белый цвет (модификатор), достаточно белый цвет прописать родительскому модификатору

2020-09-01 13:56 UTC, raccoonroman commented on source/index.html
> +          <div class="advantages__block--blue">
Ошибка: *Использование модификатора без блока или элемента, который он модифицирует* https://up.htmlacademy.ru/adaptive/20/criteries#b5

2020-09-01 13:56 UTC, raccoonroman commented on source/index.html
> +        <div class="advantages__item advantages__item--gray">
див не может быть дочерним элементом списка

2020-09-01 13:56 UTC, raccoonroman commented on source/index.html
> +          <li class="advantages__item advantages__devil">
`advantages__devil` должен быть модификатором

2020-09-01 13:56 UTC, raccoonroman commented on source/less/style.less
> +@import "variables";
подключение файла с переменными лучше подключать первым, чтобы не было ошибок. Потому что например в "global" уже могут использоваться эти самые переменные, которых на данный момент может не существовать.

2020-09-01 13:56 UTC, raccoonroman commented on source/less/style.less
> +@import "selectors";
это не selectors, это `mixins`

2020-09-01 13:56 UTC, raccoonroman commented on source/less/style.less
> +@import "selectors";
их тоже нужно подключать в самом верху, после переменных

2020-09-01 13:56 UTC, raccoonroman commented on source/less/global.less
> +  margin: 0;
сюда же можно прописать разные свойства шрифтов - семейство, размер, цвет, высота строки и т.д.

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/site.less
> +  .center();
подключение миксинов всегда должно идти первым, чтобы некоторые его свойства можно было легко переопределить в случае чего

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/site.less
> +		box-shadow: 0px 1px 0px rgba(1, 1, 1, 0.2), inset 0 1px 0 rgba(#fff, 0.2);
если значение `0` - убирай `px`

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/page.less
> +  font-family: 'PT Sans', sans-serif;
не указан альтернативный веб-безопасный шрифт. https://up.htmlacademy.ru/adaptive/20/criteries#b10
Вот здесь их можно посмотреть https://www.cssfontstack.com/

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/page.less
> +  content: "";
это свойство здесь лишнее

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/page.less
> +  top: 216px;
а если пунктов будет больше? Тогда логотип налипнет на текст. Нужно придумать решение по лучше.

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/page.less
> +  left: 108px;
если посмотреть верстку на айфоне 6, 7, 8, где ширина экрана 375рх, то логотип уже не будет по центру. Это нужно исправить

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/hero.less
> +  background-image: url("../img/bg-back-desktop@1x.jpg");
в разных файлах используются разные типы кавычек - то двойные, то одинарные. Нужно использовать какой-то один тип. https://up.htmlacademy.ru/adaptive/20/criteries#b28

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/hero.less
> +.hero--photo {
используй преимущества препроцесоров - вложенность:
```
.hero {
  ...стили

  &--photo {
    ...стили
  }
}
```

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/search.less
> +  .center;
вызывай миксин с круглыми скобками

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/form.less
> +  background: #E5E5E5;
это лучше делать обычным бордером

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/photos.less
> +	img {
делай везде пустой перенос перед вложенными селекторами, так читабельней

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/photos.less
> +		background: #E5E5E5;
лучше сделать бордером

2020-09-01 13:56 UTC, raccoonroman commented on source/less/blocks/advantages.less
> +  margin-top: 30px;
у бэм-блока не должно быть каких-то внешних отступов

2020-09-01 13:57 UTC, raccoonroman commented
файлы типа source/less/. — копия (2) — копия — копия.less так и не поудалял

2020-09-03 19:33 UTC, Rudolf31 commented on source/form.html
> +        <img src="img/text-sedona.svg" width="229px">
дописал

2020-09-03 20:03 UTC, Rudolf31 commented on source/form.html
> +        <li><a href="#" class="socials__link"><img src="img/icon-twitter.svg"  alt="">twitter</a></li>
указал и добавил

2020-09-04 19:09 UTC, Rudolf31 commented on source/index.html
> +      <img src="img/text-sedona-index.svg" width="282" class="hero__title">
указал

2020-09-04 19:10 UTC, Rudolf31 commented on source/index.html
> +          <li class="advantages__item advantages__devil">
сделал

2020-09-04 19:11 UTC, Rudolf31 commented on source/less/style.less
> +@import "variables";
переместил

2020-09-04 19:11 UTC, Rudolf31 commented on source/less/style.less
> +@import "selectors";
сделал

2020-09-04 19:14 UTC, Rudolf31 commented on source/less/global.less
> +  margin: 0;
шрифт прописал

2020-09-04 19:14 UTC, Rudolf31 commented on source/less/blocks/site.less
> +  .center();
переместил

2020-09-04 19:15 UTC, Rudolf31 commented on source/less/blocks/site.less
> +		box-shadow: 0px 1px 0px rgba(1, 1, 1, 0.2), inset 0 1px 0 rgba(#fff, 0.2);
убрал

2020-09-04 20:07 UTC, Rudolf31 commented on source/less/blocks/hero.less
> +.hero--photo {
сделал

2020-09-04 20:08 UTC, Rudolf31 commented on source/less/blocks/search.less
> +  .center;
исправил

2020-09-12 09:47 UTC, raccoonroman requested changes

2020-09-12 09:47 UTC, raccoonroman commented on source/form.html
>      <link rel="stylesheet" href="css/normalize.css">
normalize можешь удалить и не использовать

2020-09-12 09:47 UTC, raccoonroman commented on source/index.html
> +      <h1 class="advantages__title">СЕДОНА - НЕБОЛЬШОЙ<br> ГОРОДОК В АРИЗОНЕ, ЗАСЛУЖИВАЮЩИЙ БОЛЬШЕГО!</h1>
`<br>` не нужен

2020-09-12 09:47 UTC, raccoonroman commented on source/index.html
> +      <p class="advantages__description">РАССМОТРИМ 5 ПРИЧИН, ПО КОТОРЫМ<br> СЕДОНА КРУЧЕ, ЧЕМ ГРАНД КАНЬОН!</p>
`<br>` не нужен

2020-09-12 09:47 UTC, raccoonroman commented on source/index.html
> +        <li class="advantages__item advantages__block--blue">
```suggestion
        <li class="advantages__item advantages__item--blue">
```

2020-09-12 09:47 UTC, raccoonroman commented on source/index.html
> +          <li class="advantages__item advantages--devil">
Первое, это модификатор написан неправильно, должно быть так:
```suggestion
          <li class="advantages__item advantages__item--devil">
```

2020-09-12 09:47 UTC, raccoonroman commented on source/index.html
> +          <li class="advantages__item advantages--devil">
второе, это для списка и его элемента испольуется один и тот же класс - `advantages__item`. Так быть не должно

2020-09-12 09:47 UTC, raccoonroman commented on source/index.html
> +          <li class="advantages__item advantages--devil">
модификатор прописан не правильно

2020-09-12 09:47 UTC, raccoonroman commented on source/index.html
> +      <img src="img/bg-map-mobile@1x.jpg " width="320">
размеры не удалил

2020-09-12 09:47 UTC, raccoonroman commented on source/less/blocks/advantages.less
> +		position: absolute;
это проще и лучше сделать бордером

2020-09-12 09:47 UTC, raccoonroman commented on source/less/blocks/page.less
> +.page-header__logo {
файл называется page, а используется в нем бэм-блок page-header

2020-09-12 09:47 UTC, raccoonroman commented on source/less/blocks/site.less
> +		padding: 7px 5px;
замени табы на пробелы

2020-09-12 09:47 UTC, raccoonroman commented on source/less/font-face.less
> +	src: local('☺'), url('fonts/9688.woff') format('woff'), url('fonts/9688.ttf') format('truetype'), url('fonts/9688.svg') format('svg');
что это такое страшное?)

2020-09-12 09:47 UTC, raccoonroman commented on source/less/global.less
> +  font-family: "Tahoma", "PT Sans", sans-serif;
Главный шрифт должен быть `PT Sans`

2020-09-13 20:21 UTC, raccoonroman approved these changes

2020-09-13 20:22 UTC, merged